package cmd

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

func TestWriteReviewArtifactsSplitsVectorsIntoSidecar(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	reviewPath := filepath.Join(tmpDir, "scan.review.yaml")

	vec := make([]float64, embeddingDim)
	vec[0] = 1.0

	doc := ReviewDocument{
		ReviewID:     "a1b2c3d4e5f6",
		VideoID:      "vid_test",
		InputPath:    "samples/test.mp4",
			ArtifactRoot: "results/vid_test/reviews/a1b2c3d4e5f6/tracks",
			Tracks: []StagingItem{
				{
					ID: 1,
					NearestCandidates: []NearestCandidate{
						{Identity: "Jenny", Variant: "Default", Distance: 0.284},
						{Identity: "Jenna", Variant: "Default", Distance: 0.317},
				},
				Reason:         "nearest_distance=0.284, second_distance=0.317, gap=0.033 < 0.050 -> needs review",
				Action:         "new_identity",
				InternalVector: vec,
				InternalCount:  3,
			},
		},
	}

	if err := writeReviewArtifacts(reviewPath, doc); err != nil {
		t.Fatalf("writeReviewArtifacts returned error: %v", err)
	}

	reviewBytes, err := os.ReadFile(reviewPath)
	if err != nil {
		t.Fatalf("failed to read review YAML: %v", err)
	}
	reviewText := string(reviewBytes)
	if strings.Contains(reviewText, "internal_vector") || strings.Contains(reviewText, "internal_count") {
		t.Fatalf("expected review YAML to omit internal data, got:\n%s", reviewText)
	}
	if strings.Contains(reviewText, "thumbnail:") {
		t.Fatalf("expected review YAML to omit thumbnail paths, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Edit only `identity`, `variant`, and `action`.") {
		t.Fatalf("expected top-level edit guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# `review_id` is the unique identifier for this scan run and review file.") {
		t.Fatalf("expected review_id description comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Leave `review_id`, `video_id`, and `input_path` unchanged.") {
		t.Fatalf("expected top-level immutable metadata guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Leave `id`, `start_time`, `end_time`, `nearest_candidates`, `confidence`, and `reason` unchanged.") {
		t.Fatalf("expected read-only guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Valid actions: merge | new_identity | new_variant | discard.") {
		t.Fatalf("expected valid actions guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# The prefilled `action` is Sentinel's best guess from scan heuristics, not final truth.") {
		t.Fatalf("expected action heuristic guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Corresponding thumbnails and frame artifacts live under:\n#   results/vid_test/reviews/a1b2c3d4e5f6/tracks/<id>/") {
		t.Fatalf("expected artifact root guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Editable fields below are the values that will be committed.") {
		t.Fatalf("expected per-track editable guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# For `new_identity`, leave `identity` blank to let Sentinel auto-name it, and leave `variant` blank; Sentinel will create the `Default` variant.") {
		t.Fatalf("expected new_identity variant guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# For `new_variant`, set `identity` to the existing person and `variant` to the new variant name.") {
		t.Fatalf("expected new_variant guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "tracks:\n\n    # Read-only fields below are generated by scan.\n    - id: 1") {
		t.Fatalf("expected blank line and read-only comment before first review track, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "nearest_candidates:") || !strings.Contains(reviewText, "distance: 0.284") || !strings.Contains(reviewText, "distance: 0.317") {
		t.Fatalf("expected nearest_candidates with rounded distances, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "reason: nearest_distance=0.284, second_distance=0.317, gap=0.033 < 0.050 -> needs review") {
		t.Fatalf("expected concrete reason field, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "identity: \"\"") || !strings.Contains(reviewText, "variant: \"\"") {
		t.Fatalf("expected blank editable identity/variant fields to remain visible, got:\n%s", reviewText)
	}

	review, err := readReviewDocument(reviewBytes)
	if err != nil {
		t.Fatalf("readReviewDocument returned error: %v", err)
	}
	if got := len(review.Tracks); got != 1 {
		t.Fatalf("expected one review track, got %d", got)
	}
	if got := review.ReviewID; got != "a1b2c3d4e5f6" {
		t.Fatalf("expected review_id to round-trip, got %q", got)
	}
	if got := review.Tracks[0].ID; got != 1 {
		t.Fatalf("expected review id 1, got %d", got)
	}
	if got := len(review.Tracks[0].InternalVector); got != 0 {
		t.Fatalf("expected no embedded vector in YAML, got len=%d", got)
	}
		if got := review.Tracks[0].InternalCount; got != 0 {
			t.Fatalf("expected no embedded internal_count in YAML, got %d", got)
		}

		sidecarBytes, err := os.ReadFile(reviewDataFilePath(reviewPath))
	if err != nil {
		t.Fatalf("failed to read review sidecar: %v", err)
	}

	var sidecar ReviewSidecarDocument
	if err := json.Unmarshal(sidecarBytes, &sidecar); err != nil {
		t.Fatalf("failed to unmarshal review sidecar: %v", err)
	}
	if got := sidecar.ReviewID; got != "a1b2c3d4e5f6" {
		t.Fatalf("expected sidecar review_id to round-trip, got %q", got)
	}
	if got := sidecar.VideoID; got != "vid_test" {
		t.Fatalf("expected sidecar video_id to round-trip, got %q", got)
	}
	if got := sidecar.InputPath; got != "samples/test.mp4" {
		t.Fatalf("expected sidecar input_path to round-trip, got %q", got)
	}

	data, ok := sidecar.Tracks["1"]
	if !ok {
		t.Fatalf("expected sidecar data for review id 1, got %+v", sidecar.Tracks)
	}
	if got := len(data.InternalVector); got != embeddingDim {
		t.Fatalf("expected %d vector dimensions, got %d", embeddingDim, got)
	}
	if got := data.InternalCount; got != 3 {
		t.Fatalf("expected internal_count 3, got %d", got)
	}
	if data.Fingerprint == "" {
		t.Fatal("expected sidecar fingerprint to be populated")
	}
	wantFingerprint, err := reviewTrackFingerprint(doc.Tracks[0])
	if err != nil {
		t.Fatalf("reviewTrackFingerprint returned error: %v", err)
	}
	if got := data.Fingerprint; got != wantFingerprint {
		t.Fatalf("expected sidecar fingerprint %q, got %q", wantFingerprint, got)
	}
}

func TestHydrateReviewDocumentLoadsSidecarData(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	reviewPath := filepath.Join(tmpDir, "scan.review.yaml")

	vec := make([]float64, embeddingDim)
	vec[1] = 1.0

	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{
				ID:     1,
				Action: "new_identity",
			},
		},
	}
	fingerprint, err := reviewTrackFingerprint(review.Tracks[0])
	if err != nil {
		t.Fatalf("reviewTrackFingerprint returned error: %v", err)
	}

	if err := writeReviewSidecarFile(reviewDataFilePath(reviewPath), ReviewSidecarDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: map[string]ReviewTrackData{
			"1": {
				Fingerprint:    fingerprint,
				InternalVector: vec,
				InternalCount:  2,
			},
		},
	}); err != nil {
		t.Fatalf("writeReviewSidecarFile returned error: %v", err)
	}

	hydrated, err := hydrateReviewDocument(reviewPath, review)
	if err != nil {
		t.Fatalf("hydrateReviewDocument returned error: %v", err)
	}

	if got := len(hydrated.Tracks[0].InternalVector); got != embeddingDim {
		t.Fatalf("expected %d vector dimensions after hydration, got %d", embeddingDim, got)
	}
	if got := hydrated.Tracks[0].InternalCount; got != 2 {
		t.Fatalf("expected internal_count 2 after hydration, got %d", got)
	}
}

func TestHydrateReviewDocumentRejectsUnexpectedSidecarTrackData(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	reviewPath := filepath.Join(tmpDir, "scan.review.yaml")

	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{
				ID:     1,
				Action: "new_identity",
			},
		},
	}
	fingerprint, err := reviewTrackFingerprint(review.Tracks[0])
	if err != nil {
		t.Fatalf("reviewTrackFingerprint returned error: %v", err)
	}

	if err := writeReviewSidecarFile(reviewDataFilePath(reviewPath), ReviewSidecarDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: map[string]ReviewTrackData{
			"1": {
				Fingerprint:    fingerprint,
				InternalVector: make([]float64, embeddingDim),
				InternalCount:  2,
			},
			"99": {
				Fingerprint:    "extra",
				InternalVector: make([]float64, embeddingDim),
				InternalCount:  1,
			},
		},
	}); err != nil {
		t.Fatalf("writeReviewSidecarFile returned error: %v", err)
	}

	_, err = hydrateReviewDocument(reviewPath, review)
	if err == nil {
		t.Fatal("expected unexpected sidecar track data to be rejected")
	}
	if !strings.Contains(err.Error(), "unexpected track data") {
		t.Fatalf("expected unexpected track data error, got: %v", err)
	}
}

func TestHydrateReviewDocumentRejectsEmbeddedDataWithoutSidecar(t *testing.T) {
	t.Parallel()

	vec := make([]float64, embeddingDim)
	vec[2] = 1.0

	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{
				ID:             1,
				Action:         "new_identity",
				InternalVector: vec,
				InternalCount:  1,
			},
		},
	}

	_, err := hydrateReviewDocument(filepath.Join(t.TempDir(), "scan.review.yaml"), review)
	if err == nil {
		t.Fatal("expected embedded internal data to be rejected")
	}
	if !strings.Contains(err.Error(), "must not embed internal data") {
		t.Fatalf("expected embedded internal data error, got: %v", err)
	}
}

func TestHydrateReviewDocumentRequiresSidecarForActionableTracks(t *testing.T) {
	t.Parallel()

	reviewPath := filepath.Join(t.TempDir(), "scan.review.yaml")
	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{
				ID:     1,
				Action: "new_identity",
			},
		},
	}

	_, err := hydrateReviewDocument(reviewPath, review)
	if err == nil {
		t.Fatal("expected missing sidecar to be rejected")
	}
	if !strings.Contains(err.Error(), reviewDataFilePath(reviewPath)) {
		t.Fatalf("expected missing sidecar path in error, got: %v", err)
	}
}

func TestHydrateReviewDocumentRequiresSidecarForDiscardOnlyReviews(t *testing.T) {
	t.Parallel()

	reviewPath := filepath.Join(t.TempDir(), "scan.review.yaml")
	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{
				ID:     1,
				Action: "discard",
			},
		},
	}

	_, err := hydrateReviewDocument(reviewPath, review)
	if err == nil {
		t.Fatal("expected missing sidecar to be rejected for discard-only reviews")
	}
	if !strings.Contains(err.Error(), reviewDataFilePath(reviewPath)) {
		t.Fatalf("expected missing sidecar path in error, got: %v", err)
	}
}

func TestHydrateReviewDocumentRequiresSidecarForEmptyReviews(t *testing.T) {
	t.Parallel()

	reviewPath := filepath.Join(t.TempDir(), "scan.review.yaml")
	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
	}

	_, err := hydrateReviewDocument(reviewPath, review)
	if err == nil {
		t.Fatal("expected missing sidecar to be rejected for empty reviews")
	}
	if !strings.Contains(err.Error(), reviewDataFilePath(reviewPath)) {
		t.Fatalf("expected missing sidecar path in error, got: %v", err)
	}
}

func TestHydrateReviewDocumentAllowsEmptyReviewWithMatchingSidecar(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	reviewPath := filepath.Join(tmpDir, "scan.review.yaml")

	if err := writeReviewSidecarFile(reviewDataFilePath(reviewPath), ReviewSidecarDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks:    map[string]ReviewTrackData{},
	}); err != nil {
		t.Fatalf("writeReviewSidecarFile returned error: %v", err)
	}

	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks:    []StagingItem{},
	}

	hydrated, err := hydrateReviewDocument(reviewPath, review)
	if err != nil {
		t.Fatalf("expected empty review with matching sidecar to hydrate, got error: %v", err)
	}
	if len(hydrated.Tracks) != 0 {
		t.Fatalf("expected hydrated empty review to keep zero tracks, got %d", len(hydrated.Tracks))
	}
}

func TestHydrateReviewDocumentRejectsMissingSidecarTrackData(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	reviewPath := filepath.Join(tmpDir, "scan.review.yaml")

	if err := writeReviewSidecarFile(reviewDataFilePath(reviewPath), ReviewSidecarDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks:    map[string]ReviewTrackData{},
	}); err != nil {
		t.Fatalf("writeReviewSidecarFile returned error: %v", err)
	}

	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{
				ID:     1,
				Action: "discard",
			},
		},
	}

	_, err := hydrateReviewDocument(reviewPath, review)
	if err == nil {
		t.Fatal("expected missing sidecar track data to be rejected")
	}
	if !strings.Contains(err.Error(), "missing track data") {
		t.Fatalf("expected missing track data error, got: %v", err)
	}
}

func TestPrepareReviewArtifactsRootClearsStaleTracks(t *testing.T) {
	t.Parallel()

	reviewArtifactsDir := filepath.Join(t.TempDir(), "reviews", "a1b2c3d4e5f6")
	staleFile := filepath.Join(reviewArtifactsDir, "tracks", "1", "frames", "stale.jpg")
	if err := os.MkdirAll(filepath.Dir(staleFile), 0755); err != nil {
		t.Fatalf("failed to create stale artifact dir: %v", err)
	}
	if err := os.WriteFile(staleFile, []byte("stale"), 0644); err != nil {
		t.Fatalf("failed to seed stale artifact: %v", err)
	}

	if err := prepareReviewArtifactsRoot(reviewArtifactsDir); err != nil {
		t.Fatalf("prepareReviewArtifactsRoot returned error: %v", err)
	}

	if _, err := os.Stat(staleFile); !os.IsNotExist(err) {
		t.Fatalf("expected stale artifact to be removed, stat err=%v", err)
	}
	if info, err := os.Stat(filepath.Join(reviewArtifactsDir, "tracks")); err != nil {
		t.Fatalf("expected tracks root to be recreated, got error: %v", err)
	} else if !info.IsDir() {
		t.Fatalf("expected recreated tracks root to be a directory")
	}
}

func TestReviewArtifactCommentRootMatchesRuntimeMode(t *testing.T) {
	t.Parallel()

	if got := reviewArtifactCommentRoot("/data", "vid_test", "a1b2c3d4e5f6"); got != filepath.Join("results", "vid_test", "reviews", "a1b2c3d4e5f6", "tracks") {
		t.Fatalf("expected docker comment root to be host-facing results path, got %q", got)
	}
	if got := reviewArtifactCommentRoot("data", "vid_test", "a1b2c3d4e5f6"); got != filepath.Join("data", "results", "vid_test", "reviews", "a1b2c3d4e5f6", "tracks") {
		t.Fatalf("expected local comment root to include data/ prefix, got %q", got)
	}
}

func TestHydrateReviewDocumentRejectsMismatchedSidecarMetadata(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	reviewPath := filepath.Join(tmpDir, "scan.review.yaml")

	vec := make([]float64, embeddingDim)
	vec[3] = 1.0

	if err := writeReviewSidecarFile(reviewDataFilePath(reviewPath), ReviewSidecarDocument{
		ReviewID:  "deadbeefcafe",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: map[string]ReviewTrackData{
			"1": {
				InternalVector: vec,
				InternalCount:  2,
			},
		},
	}); err != nil {
		t.Fatalf("writeReviewSidecarFile returned error: %v", err)
	}

	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{ID: 1, Action: "new_identity"},
		},
	}

	_, err := hydrateReviewDocument(reviewPath, review)
	if err == nil {
		t.Fatal("expected mismatched sidecar metadata to be rejected")
	}
	if !strings.Contains(err.Error(), "review_id") {
		t.Fatalf("expected review_id mismatch error, got: %v", err)
	}
}

func TestHydrateReviewDocumentRejectsMismatchedTrackFingerprint(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	reviewPath := filepath.Join(tmpDir, "scan.review.yaml")

	vec := make([]float64, embeddingDim)
	vec[4] = 1.0

	if err := writeReviewSidecarFile(reviewDataFilePath(reviewPath), ReviewSidecarDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: map[string]ReviewTrackData{
			"1": {
				Fingerprint:    "deadbeef",
				InternalVector: vec,
				InternalCount:  2,
			},
		},
	}); err != nil {
		t.Fatalf("writeReviewSidecarFile returned error: %v", err)
	}

	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{
				ID:         1,
				StartTime:  0,
				EndTime:    1,
				Confidence: 0.84,
				Reason:     "nearest_distance=0.284 <= merge_cutoff=0.350 -> suggested merge",
				Action:     "merge",
				Identity:   "Jenny",
				Variant:    "Default",
				NearestCandidates: []NearestCandidate{
					{Identity: "Jenny", Variant: "Default", Distance: 0.284},
				},
			},
		},
	}

	_, err := hydrateReviewDocument(reviewPath, review)
	if err == nil {
		t.Fatal("expected mismatched track fingerprint to be rejected")
	}
	if !strings.Contains(err.Error(), "fingerprint mismatch") {
		t.Fatalf("expected fingerprint mismatch error, got: %v", err)
	}
}

func TestNewReviewIDIsTwelveHexChars(t *testing.T) {
	t.Parallel()

	id, err := newReviewID()
	if err != nil {
		t.Fatalf("newReviewID returned error: %v", err)
	}
	if len(id) != 12 {
		t.Fatalf("expected 12-char review_id, got %q", id)
	}
	if !regexp.MustCompile(`^[0-9a-f]{12}$`).MatchString(id) {
		t.Fatalf("expected lowercase hex review_id, got %q", id)
	}
}

func TestShortDisplayIDTruncatesForLogs(t *testing.T) {
	t.Parallel()

	if got := shortDisplayID("abcdef1234567890"); got != "abcdef123456" {
		t.Fatalf("expected truncated display id, got %q", got)
	}
	if got := shortDisplayID("abcdef123456"); got != "abcdef123456" {
		t.Fatalf("expected equal-length id to remain unchanged, got %q", got)
	}
}

func TestDefaultReviewFilePathUsesVideoAndReviewIDs(t *testing.T) {
	t.Parallel()

	if got := defaultReviewFilePath("samples/1.mp4", "c46b22a303430d0d4f2477196dd10ece118b9488c25a3ffa05b1513948e16939", "a1b2c3d4e5f6"); got != filepath.Join("data", "reviews", "1.c46b22a30343.a1b2c3d4e5f6.review.yaml") {
		t.Fatalf("unexpected default review file path: %q", got)
	}
}
