package cmd

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestWriteReviewArtifactsSplitsVectorsIntoSidecar(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	reviewPath := filepath.Join(tmpDir, "scan.review.yaml")

	vec := make([]float64, embeddingDim)
	vec[0] = 1.0

	doc := ReviewDocument{
		ReviewID:     "a1b2c3d4e5f6",
		VideoID:      "vid_test",
		InputPath:    "samples/test.mp4",
		ArtifactRoot: "results/vid_test/reviews/a1b2c3d4e5f6/tracks",
		Tracks: []StagingItem{
			{
				ID: 1,
				NearestCandidates: []NearestCandidate{
					{Identity: "Jenny", Variant: "Default", Distance: 0.284},
					{Identity: "Jenna", Variant: "Default", Distance: 0.317},
				},
				Confidence:     0.86,
				Action:         "new_identity",
				InternalVector: vec,
				InternalCount:  3,
			},
		},
		SummaryItems: []reviewSummaryItem{
			{
				ID:        1,
				StartTime: 0,
				EndTime:   0,
				NearestCandidates: []NearestCandidate{
					{Identity: "Jenny", Variant: "Default", Distance: 0.284},
					{Identity: "Jenna", Variant: "Default", Distance: 0.317},
				},
				Confidence:  0.86,
				Action:      "new_identity",
				ArtifactDir: "results/vid_test/reviews/a1b2c3d4e5f6/tracks/1",
				Vector:      vec,
				Count:       3,
			},
		},
	}

	if err := writeReviewArtifacts(reviewPath, doc); err != nil {
		t.Fatalf("writeReviewArtifacts returned error: %v", err)
	}

	reviewBytes, err := os.ReadFile(reviewPath)
	if err != nil {
		t.Fatalf("failed to read review YAML: %v", err)
	}
	reviewText := string(reviewBytes)
	if strings.Contains(reviewText, "internal_vector") || strings.Contains(reviewText, "internal_count") {
		t.Fatalf("expected review YAML to omit internal data, got:\n%s", reviewText)
	}
	if strings.Contains(reviewText, "thumbnail:") {
		t.Fatalf("expected review YAML to omit thumbnail paths, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Leave top-level `raw_tracks`, `unresolved_tracks`, `review_id`, `video_id`, and `input_path` unchanged.") {
		t.Fatalf("expected top-level immutable guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Edit only `potential_identities[].tracks`, `potential_identities[].identity`, `potential_identities[].variant`, and `potential_identities[].action`.") {
		t.Fatalf("expected top-level edit guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# `review_id` is the unique identifier for this scan run and review file.") {
		t.Fatalf("expected review_id description comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Each `potential_identities[].tracks` entry must use either a <track_id> or an inclusive <start>-<end> range of track IDs listed under `raw_tracks`.") {
		t.Fatalf("expected track membership guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# `unresolved_tracks` is read-only. To resolve one, add its <track_id> to a `potential_identities[].tracks` entry or create a new potential identity entry.") {
		t.Fatalf("expected unresolved_tracks guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Leave `raw_tracks.*.start_time`, `raw_tracks.*.end_time`, `raw_tracks.*.nearest_candidates`, `raw_tracks.*.confidence`, `raw_tracks.*.suggested_identity`, `raw_tracks.*.suggested_variant`, `raw_tracks.*.suggested_action`, and `raw_tracks.*.artifact_dir` unchanged.") {
		t.Fatalf("expected read-only guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Leave each `potential_identities[].id` unchanged.") {
		t.Fatalf("expected potential identity id guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Valid actions: merge | new_identity | new_variant | discard.") {
		t.Fatalf("expected valid actions guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# The prefilled `action` is Sentinel's best guess from scan heuristics, not final truth.") {
		t.Fatalf("expected action heuristic guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Each `raw_tracks.<track_id>.artifact_dir` points to corresponding thumbnails and frame artifacts under:\n#   results/vid_test/reviews/a1b2c3d4e5f6/tracks/<track_id>/") {
		t.Fatalf("expected artifact root guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "raw_tracks:\n\n    # Read-only track evidence below is generated by scan.") {
		t.Fatalf("expected raw_tracks read-only section comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "potential_identities:\n\n    # Editable potential identities below control track membership and the values that will be committed.") {
		t.Fatalf("expected potential_identities editable section comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Edit `tracks` to move <track_id> entries or <start>-<end> ranges between potential identities.") {
		t.Fatalf("expected track editing guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# For `new_identity`, if `identity` is left blank, then Sentinel will auto-name it. If `variant` is left blank, then Sentinel will create the `Default` variant.") {
		t.Fatalf("expected new_identity guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# For `new_variant`, set `identity` to the existing person and `variant` to the new variant name.") {
		t.Fatalf("expected new_variant guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "\n\n    # Leave `id` unchanged.\n    - id: 1") {
		t.Fatalf("expected blank line and read-only comment before first potential identity, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "nearest_candidates:") || !strings.Contains(reviewText, "distance: 0.284") || !strings.Contains(reviewText, "distance: 0.317") {
		t.Fatalf("expected nearest_candidates with rounded distances, got:\n%s", reviewText)
	}
	if strings.Contains(reviewText, "\n    reason:") || strings.Contains(reviewText, "\n      reason:") {
		t.Fatalf("expected grouped review YAML to omit verbose reason fields, got:\n%s", reviewText)
	}
	if strings.Index(reviewText, "confidence:") > strings.Index(reviewText, "potential_identities:\n\n    # Editable potential identities below control track membership and the values that will be committed.") {
		t.Fatalf("expected confidence to remain in the raw_tracks evidence section above potential identities, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "suggested_action: new_identity") {
		t.Fatalf("expected per-track suggested_action in raw track evidence, got:\n%s", reviewText)
	}

	var reviewFile ReviewFileDocument
	if err := yaml.Unmarshal(reviewBytes, &reviewFile); err != nil {
		t.Fatalf("failed to unmarshal grouped review YAML: %v", err)
	}
	if got := reviewFile.ReviewID; got != "a1b2c3d4e5f6" {
		t.Fatalf("expected review_id to round-trip, got %q", got)
	}
	if got := len(reviewFile.PotentialIdentities); got != 1 {
		t.Fatalf("expected one potential identity, got %d", got)
	}
	if got := len(reviewFile.UnresolvedTracks); got != 0 {
		t.Fatalf("expected no unresolved tracks, got %d", got)
	}
	if got := len(reviewFile.RawTracks); got != 1 {
		t.Fatalf("expected one raw track entry, got %d", got)
	}
	if got := reviewFile.PotentialIdentities[0].ID; got != 1 {
		t.Fatalf("expected potential identity id 1, got %d", got)
	}
	if got := reviewFile.PotentialIdentities[0].Tracks; len(got) != 1 || got[0] != "1" {
		t.Fatalf("expected grouped track selector [\"1\"], got %v", got)
	}
	if got := reviewFile.RawTracks["1"].ArtifactDir; got != "results/vid_test/reviews/a1b2c3d4e5f6/tracks/1" {
		t.Fatalf("expected raw track artifact_dir to round-trip, got %q", got)
	}
	if got := reviewFile.RawTracks["1"].SuggestedAction; got != "new_identity" {
		t.Fatalf("expected raw track suggested_action to round-trip, got %q", got)
	}
	if got := reviewFile.PotentialIdentities[0].Action; got != "new_identity" {
		t.Fatalf("expected conservative group action prefill to remain new_identity for singleton, got %q", got)
	}

	sidecarBytes, err := os.ReadFile(reviewDataFilePath(reviewPath))
	if err != nil {
		t.Fatalf("failed to read review sidecar: %v", err)
	}

	var sidecar ReviewSidecarDocument
	if err := json.Unmarshal(sidecarBytes, &sidecar); err != nil {
		t.Fatalf("failed to unmarshal review sidecar: %v", err)
	}
	if got := sidecar.ReviewID; got != "a1b2c3d4e5f6" {
		t.Fatalf("expected sidecar review_id to round-trip, got %q", got)
	}
	if got := sidecar.VideoID; got != "vid_test" {
		t.Fatalf("expected sidecar video_id to round-trip, got %q", got)
	}
	if got := sidecar.InputPath; got != "samples/test.mp4" {
		t.Fatalf("expected sidecar input_path to round-trip, got %q", got)
	}

	data, ok := sidecar.Tracks["1"]
	if !ok {
		t.Fatalf("expected sidecar data for review id 1, got %+v", sidecar.Tracks)
	}
	if got := len(data.InternalVector); got != embeddingDim {
		t.Fatalf("expected %d vector dimensions, got %d", embeddingDim, got)
	}
	if got := data.InternalCount; got != 3 {
		t.Fatalf("expected internal_count 3, got %d", got)
	}
	if data.Fingerprint == "" {
		t.Fatal("expected sidecar fingerprint to be populated")
	}
	wantFingerprint, err := reviewTrackFingerprint(doc.Tracks[0])
	if err != nil {
		t.Fatalf("reviewTrackFingerprint returned error: %v", err)
	}
	if got := data.Fingerprint; got != wantFingerprint {
		t.Fatalf("expected sidecar fingerprint %q, got %q", wantFingerprint, got)
	}
}

func TestWriteReviewArtifactsSeparatesUnresolvedTracksFromPotentialIdentities(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	reviewPath := filepath.Join(tmpDir, "scan.review.yaml")

	vec1 := make([]float64, embeddingDim)
	vec1[0] = 0.819
	vec1[1] = 0.574
	vec2 := make([]float64, embeddingDim)
	vec2[0] = 0.819
	vec2[1] = -0.574
	vec3 := make([]float64, embeddingDim)
	vec3[0] = 1.0

	doc := ReviewDocument{
		ReviewID:     "a1b2c3d4e5f6",
		VideoID:      "vid_test",
		InputPath:    "samples/test.mp4",
		ArtifactRoot: "results/vid_test/reviews/a1b2c3d4e5f6/tracks",
		Tracks: []StagingItem{
			{ID: 1, StartTime: 0, EndTime: 2},
			{ID: 2, StartTime: 3, EndTime: 5},
			{ID: 3, StartTime: 6, EndTime: 8},
		},
		SummaryItems: []reviewSummaryItem{
			{ID: 1, StartTime: 0, EndTime: 2, Vector: vec1, Count: 3, Action: "new_identity"},
			{ID: 2, StartTime: 3, EndTime: 5, Vector: vec2, Count: 3, Action: "new_identity"},
			{ID: 3, StartTime: 6, EndTime: 8, Vector: vec3, Count: 3, Action: "new_identity"},
		},
	}

	if err := writeReviewArtifacts(reviewPath, doc); err != nil {
		t.Fatalf("writeReviewArtifacts returned error: %v", err)
	}

	reviewBytes, err := os.ReadFile(reviewPath)
	if err != nil {
		t.Fatalf("failed to read review YAML: %v", err)
	}

	var reviewFile ReviewFileDocument
	if err := yaml.Unmarshal(reviewBytes, &reviewFile); err != nil {
		t.Fatalf("failed to unmarshal grouped review YAML: %v", err)
	}

	if got := len(reviewFile.PotentialIdentities); got != 2 {
		t.Fatalf("expected two potential identities, got %d", got)
	}
	if got := len(reviewFile.RawTracks); got != 3 {
		t.Fatalf("expected three raw track entries, got %d", got)
	}
	if got := reviewFile.UnresolvedTracks; len(got) != 1 || got[0] != "3" {
		t.Fatalf("expected unresolved_tracks [\"3\"], got %v", got)
	}
	if !strings.Contains(string(reviewBytes), "unresolved_tracks:\n\n    # Read-only unresolved track IDs below were not confidently grouped during scan.\n") {
		t.Fatalf("expected unresolved_tracks read-only section comment, got:\n%s", string(reviewBytes))
	}
	if got := reviewFile.PotentialIdentities[0].Tracks; len(got) != 1 || got[0] != "1" {
		t.Fatalf("expected first potential identity to contain raw track 1, got %v", got)
	}
	if got := reviewFile.PotentialIdentities[1].Tracks; len(got) != 1 || got[0] != "2" {
		t.Fatalf("expected second potential identity to contain raw track 2, got %v", got)
	}
}

func TestReviewPotentialIdentityItemOnlyPrefillsWhenAllMembersBroadlyAgree(t *testing.T) {
	t.Parallel()

	agreeing := []PotentialIdentityMember{
		{Item: reviewSummaryItem{ID: 1, Identity: "Monica", Variant: "Default", Action: "merge"}},
		{Item: reviewSummaryItem{ID: 4, Identity: "Monica", Variant: "Default", Action: "merge"}},
	}
	item := reviewPotentialIdentityItem(1, agreeing)
	if item.Identity != "Monica" || item.Variant != "Default" || item.Action != "merge" {
		t.Fatalf("expected full prefill for unanimous merge suggestion, got %+v", item)
	}

	mixedAction := []PotentialIdentityMember{
		{Item: reviewSummaryItem{ID: 1, Identity: "Monica", Variant: "Default", Action: "merge"}},
		{Item: reviewSummaryItem{ID: 4, Identity: "Monica", Variant: "", Action: "new_variant"}},
	}
	item = reviewPotentialIdentityItem(1, mixedAction)
	if item.Identity != "Monica" || item.Variant != "" || item.Action != "" {
		t.Fatalf("expected identity-only prefill when members agree on person but not action/variant, got %+v", item)
	}

	conflicting := []PotentialIdentityMember{
		{Item: reviewSummaryItem{ID: 1, Identity: "Monica", Variant: "Default", Action: "merge"}},
		{Item: reviewSummaryItem{ID: 4, Identity: "Phoebe", Variant: "Default", Action: "merge"}},
	}
	item = reviewPotentialIdentityItem(1, conflicting)
	if item.Identity != "" || item.Variant != "" || item.Action != "" {
		t.Fatalf("expected blank prefill for conflicting members, got %+v", item)
	}
}

func TestHydrateReviewDocumentLoadsSidecarData(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	reviewPath := filepath.Join(tmpDir, "scan.review.yaml")

	vec := make([]float64, embeddingDim)
	vec[1] = 1.0

	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{
				ID:     1,
				Action: "new_identity",
			},
		},
	}
	fingerprint, err := reviewTrackFingerprint(review.Tracks[0])
	if err != nil {
		t.Fatalf("reviewTrackFingerprint returned error: %v", err)
	}

	if err := writeReviewSidecarFile(reviewDataFilePath(reviewPath), ReviewSidecarDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: map[string]ReviewTrackData{
			"1": {
				Fingerprint:    fingerprint,
				InternalVector: vec,
				InternalCount:  2,
			},
		},
	}); err != nil {
		t.Fatalf("writeReviewSidecarFile returned error: %v", err)
	}

	hydrated, err := hydrateReviewDocument(reviewPath, review)
	if err != nil {
		t.Fatalf("hydrateReviewDocument returned error: %v", err)
	}

	if got := len(hydrated.Tracks[0].InternalVector); got != embeddingDim {
		t.Fatalf("expected %d vector dimensions after hydration, got %d", embeddingDim, got)
	}
	if got := hydrated.Tracks[0].InternalCount; got != 2 {
		t.Fatalf("expected internal_count 2 after hydration, got %d", got)
	}
}

func TestHydrateReviewDocumentRejectsUnexpectedSidecarTrackData(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	reviewPath := filepath.Join(tmpDir, "scan.review.yaml")

	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{
				ID:     1,
				Action: "new_identity",
			},
		},
	}
	fingerprint, err := reviewTrackFingerprint(review.Tracks[0])
	if err != nil {
		t.Fatalf("reviewTrackFingerprint returned error: %v", err)
	}

	if err := writeReviewSidecarFile(reviewDataFilePath(reviewPath), ReviewSidecarDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: map[string]ReviewTrackData{
			"1": {
				Fingerprint:    fingerprint,
				InternalVector: make([]float64, embeddingDim),
				InternalCount:  2,
			},
			"99": {
				Fingerprint:    "extra",
				InternalVector: make([]float64, embeddingDim),
				InternalCount:  1,
			},
		},
	}); err != nil {
		t.Fatalf("writeReviewSidecarFile returned error: %v", err)
	}

	_, err = hydrateReviewDocument(reviewPath, review)
	if err == nil {
		t.Fatal("expected unexpected sidecar track data to be rejected")
	}
	if !strings.Contains(err.Error(), "unexpected track data") {
		t.Fatalf("expected unexpected track data error, got: %v", err)
	}
}

func TestHydrateReviewDocumentRejectsEmbeddedDataWithoutSidecar(t *testing.T) {
	t.Parallel()

	vec := make([]float64, embeddingDim)
	vec[2] = 1.0

	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{
				ID:             1,
				Action:         "new_identity",
				InternalVector: vec,
				InternalCount:  1,
			},
		},
	}

	_, err := hydrateReviewDocument(filepath.Join(t.TempDir(), "scan.review.yaml"), review)
	if err == nil {
		t.Fatal("expected embedded internal data to be rejected")
	}
	if !strings.Contains(err.Error(), "must not embed internal data") {
		t.Fatalf("expected embedded internal data error, got: %v", err)
	}
}

func TestHydrateReviewDocumentRequiresSidecarForActionableTracks(t *testing.T) {
	t.Parallel()

	reviewPath := filepath.Join(t.TempDir(), "scan.review.yaml")
	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{
				ID:     1,
				Action: "new_identity",
			},
		},
	}

	_, err := hydrateReviewDocument(reviewPath, review)
	if err == nil {
		t.Fatal("expected missing sidecar to be rejected")
	}
	if !strings.Contains(err.Error(), reviewDataFilePath(reviewPath)) {
		t.Fatalf("expected missing sidecar path in error, got: %v", err)
	}
}

func TestHydrateReviewDocumentRequiresSidecarForDiscardOnlyReviews(t *testing.T) {
	t.Parallel()

	reviewPath := filepath.Join(t.TempDir(), "scan.review.yaml")
	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{
				ID:     1,
				Action: "discard",
			},
		},
	}

	_, err := hydrateReviewDocument(reviewPath, review)
	if err == nil {
		t.Fatal("expected missing sidecar to be rejected for discard-only reviews")
	}
	if !strings.Contains(err.Error(), reviewDataFilePath(reviewPath)) {
		t.Fatalf("expected missing sidecar path in error, got: %v", err)
	}
}

func TestHydrateReviewDocumentRequiresSidecarForEmptyReviews(t *testing.T) {
	t.Parallel()

	reviewPath := filepath.Join(t.TempDir(), "scan.review.yaml")
	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
	}

	_, err := hydrateReviewDocument(reviewPath, review)
	if err == nil {
		t.Fatal("expected missing sidecar to be rejected for empty reviews")
	}
	if !strings.Contains(err.Error(), reviewDataFilePath(reviewPath)) {
		t.Fatalf("expected missing sidecar path in error, got: %v", err)
	}
}

func TestHydrateReviewDocumentAllowsEmptyReviewWithMatchingSidecar(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	reviewPath := filepath.Join(tmpDir, "scan.review.yaml")

	if err := writeReviewSidecarFile(reviewDataFilePath(reviewPath), ReviewSidecarDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks:    map[string]ReviewTrackData{},
	}); err != nil {
		t.Fatalf("writeReviewSidecarFile returned error: %v", err)
	}

	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks:    []StagingItem{},
	}

	hydrated, err := hydrateReviewDocument(reviewPath, review)
	if err != nil {
		t.Fatalf("expected empty review with matching sidecar to hydrate, got error: %v", err)
	}
	if len(hydrated.Tracks) != 0 {
		t.Fatalf("expected hydrated empty review to keep zero tracks, got %d", len(hydrated.Tracks))
	}
}

func TestHydrateReviewDocumentRejectsMissingSidecarTrackData(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	reviewPath := filepath.Join(tmpDir, "scan.review.yaml")

	if err := writeReviewSidecarFile(reviewDataFilePath(reviewPath), ReviewSidecarDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks:    map[string]ReviewTrackData{},
	}); err != nil {
		t.Fatalf("writeReviewSidecarFile returned error: %v", err)
	}

	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{
				ID:     1,
				Action: "discard",
			},
		},
	}

	_, err := hydrateReviewDocument(reviewPath, review)
	if err == nil {
		t.Fatal("expected missing sidecar track data to be rejected")
	}
	if !strings.Contains(err.Error(), "missing track data") {
		t.Fatalf("expected missing track data error, got: %v", err)
	}
}

func TestPrepareReviewArtifactsRootClearsStaleTracks(t *testing.T) {
	t.Parallel()

	reviewArtifactsDir := filepath.Join(t.TempDir(), "reviews", "a1b2c3d4e5f6")
	staleFile := filepath.Join(reviewArtifactsDir, "tracks", "1", "frames", "stale.jpg")
	if err := os.MkdirAll(filepath.Dir(staleFile), 0755); err != nil {
		t.Fatalf("failed to create stale artifact dir: %v", err)
	}
	if err := os.WriteFile(staleFile, []byte("stale"), 0644); err != nil {
		t.Fatalf("failed to seed stale artifact: %v", err)
	}

	if err := prepareReviewArtifactsRoot(reviewArtifactsDir); err != nil {
		t.Fatalf("prepareReviewArtifactsRoot returned error: %v", err)
	}

	if _, err := os.Stat(staleFile); !os.IsNotExist(err) {
		t.Fatalf("expected stale artifact to be removed, stat err=%v", err)
	}
	if info, err := os.Stat(filepath.Join(reviewArtifactsDir, "tracks")); err != nil {
		t.Fatalf("expected tracks root to be recreated, got error: %v", err)
	} else if !info.IsDir() {
		t.Fatalf("expected recreated tracks root to be a directory")
	}
}

func TestReviewArtifactCommentRootMatchesRuntimeMode(t *testing.T) {
	t.Parallel()

	if got := reviewArtifactCommentRoot("/data", "vid_test", "a1b2c3d4e5f6"); got != filepath.Join("results", "vid_test", "reviews", "a1b2c3d4e5f6", "tracks") {
		t.Fatalf("expected docker comment root to be host-facing results path, got %q", got)
	}
	if got := reviewArtifactCommentRoot("data", "vid_test", "a1b2c3d4e5f6"); got != filepath.Join("data", "results", "vid_test", "reviews", "a1b2c3d4e5f6", "tracks") {
		t.Fatalf("expected local comment root to include data/ prefix, got %q", got)
	}
}

func TestHydrateReviewDocumentRejectsMismatchedSidecarMetadata(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	reviewPath := filepath.Join(tmpDir, "scan.review.yaml")

	vec := make([]float64, embeddingDim)
	vec[3] = 1.0

	if err := writeReviewSidecarFile(reviewDataFilePath(reviewPath), ReviewSidecarDocument{
		ReviewID:  "deadbeefcafe",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: map[string]ReviewTrackData{
			"1": {
				InternalVector: vec,
				InternalCount:  2,
			},
		},
	}); err != nil {
		t.Fatalf("writeReviewSidecarFile returned error: %v", err)
	}

	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{ID: 1, Action: "new_identity"},
		},
	}

	_, err := hydrateReviewDocument(reviewPath, review)
	if err == nil {
		t.Fatal("expected mismatched sidecar metadata to be rejected")
	}
	if !strings.Contains(err.Error(), "review_id") {
		t.Fatalf("expected review_id mismatch error, got: %v", err)
	}
}

func TestHydrateReviewDocumentRejectsMismatchedTrackFingerprint(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	reviewPath := filepath.Join(tmpDir, "scan.review.yaml")

	vec := make([]float64, embeddingDim)
	vec[4] = 1.0

	if err := writeReviewSidecarFile(reviewDataFilePath(reviewPath), ReviewSidecarDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: map[string]ReviewTrackData{
			"1": {
				Fingerprint:    "deadbeef",
				InternalVector: vec,
				InternalCount:  2,
			},
		},
	}); err != nil {
		t.Fatalf("writeReviewSidecarFile returned error: %v", err)
	}

	review := ReviewDocument{
		ReviewID:  "a1b2c3d4e5f6",
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{
				ID:         1,
				StartTime:  0,
				EndTime:    1,
				Confidence: 0.84,
				Action:     "merge",
				Identity:   "Jenny",
				Variant:    "Default",
				NearestCandidates: []NearestCandidate{
					{Identity: "Jenny", Variant: "Default", Distance: 0.284},
				},
			},
		},
	}

	_, err := hydrateReviewDocument(reviewPath, review)
	if err == nil {
		t.Fatal("expected mismatched track fingerprint to be rejected")
	}
	if !strings.Contains(err.Error(), "fingerprint mismatch") {
		t.Fatalf("expected fingerprint mismatch error, got: %v", err)
	}
}

func TestNewReviewIDIsTwelveHexChars(t *testing.T) {
	t.Parallel()

	id, err := newReviewID()
	if err != nil {
		t.Fatalf("newReviewID returned error: %v", err)
	}
	if len(id) != 12 {
		t.Fatalf("expected 12-char review_id, got %q", id)
	}
	if !regexp.MustCompile(`^[0-9a-f]{12}$`).MatchString(id) {
		t.Fatalf("expected lowercase hex review_id, got %q", id)
	}
}

func TestShortDisplayIDTruncatesForLogs(t *testing.T) {
	t.Parallel()

	if got := shortDisplayID("abcdef1234567890"); got != "abcdef123456" {
		t.Fatalf("expected truncated display id, got %q", got)
	}
	if got := shortDisplayID("abcdef123456"); got != "abcdef123456" {
		t.Fatalf("expected equal-length id to remain unchanged, got %q", got)
	}
}

func TestDefaultReviewFilePathUsesVideoAndReviewIDs(t *testing.T) {
	t.Parallel()

	if got := defaultReviewFilePath("samples/1.mp4", "c46b22a303430d0d4f2477196dd10ece118b9488c25a3ffa05b1513948e16939", "a1b2c3d4e5f6"); got != filepath.Join("data", "reviews", "1.c46b22a30343.a1b2c3d4e5f6.review.yaml") {
		t.Fatalf("unexpected default review file path: %q", got)
	}
}
