package cmd

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestWriteReviewArtifactsSplitsVectorsIntoSidecar(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	reviewPath := filepath.Join(tmpDir, "scan.review.yaml")

	vec := make([]float64, embeddingDim)
	vec[0] = 1.0

	doc := ReviewDocument{
		VideoID:      "vid_test",
		InputPath:    "samples/test.mp4",
		ArtifactRoot: "results/vid_test/tracks",
		Tracks: []StagingItem{
			{
				ID:        1,
				Thumbnail: "results/vid_test/tracks/1/3_Highest_Confidence_[0.99].jpg",
				NearestCandidates: []NearestCandidate{
					{Identity: "Jenny", Variant: "Default", Distance: 0.284},
					{Identity: "Jenna", Variant: "Default", Distance: 0.317},
				},
				Reason:         "nearest_distance=0.284, second_distance=0.317, gap=0.033 < 0.050 -> needs review",
				Action:         "new_identity",
				InternalVector: vec,
				InternalCount:  3,
			},
		},
	}

	if err := writeReviewArtifacts(reviewPath, doc); err != nil {
		t.Fatalf("writeReviewArtifacts returned error: %v", err)
	}

	reviewBytes, err := os.ReadFile(reviewPath)
	if err != nil {
		t.Fatalf("failed to read review YAML: %v", err)
	}
	reviewText := string(reviewBytes)
	if strings.Contains(reviewText, "internal_vector") || strings.Contains(reviewText, "internal_count") {
		t.Fatalf("expected review YAML to omit internal data, got:\n%s", reviewText)
	}
	if strings.Contains(reviewText, "thumbnail:") {
		t.Fatalf("expected review YAML to omit thumbnail paths, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Edit only `identity`, `variant`, and `action`.") {
		t.Fatalf("expected top-level edit guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Leave `id`, `start_time`, `end_time`, `nearest_candidates`, `confidence`, and `reason` unchanged.") {
		t.Fatalf("expected read-only guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Valid actions: merge | new_identity | new_variant | discard.") {
		t.Fatalf("expected valid actions guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# The prefilled `action` is Sentinel's best guess from scan heuristics, not final truth.") {
		t.Fatalf("expected action heuristic guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Optional: add `notes` under any track if you want to leave reviewer context.") {
		t.Fatalf("expected notes guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Corresponding thumbnails and frame artifacts live under:\n#   results/vid_test/tracks/<id>/") {
		t.Fatalf("expected artifact root guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Editable fields below are the values that will be committed.") {
		t.Fatalf("expected per-track editable guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# For `new_identity`, leave `variant` blank; Sentinel will create the `Default` variant.") {
		t.Fatalf("expected new_identity variant guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# For `new_variant`, set `identity` to the existing person and `variant` to the new variant name.") {
		t.Fatalf("expected new_variant guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "# Optional: add `notes` if you want to leave reviewer context for this track.") {
		t.Fatalf("expected per-track notes guidance comment, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "tracks:\n\n    # Read-only fields below are generated by scan.\n    - id: 1") {
		t.Fatalf("expected blank line and read-only comment before first review track, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "nearest_candidates:") || !strings.Contains(reviewText, "distance: 0.284") || !strings.Contains(reviewText, "distance: 0.317") {
		t.Fatalf("expected nearest_candidates with rounded distances, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "reason: nearest_distance=0.284, second_distance=0.317, gap=0.033 < 0.050 -> needs review") {
		t.Fatalf("expected concrete reason field, got:\n%s", reviewText)
	}
	if !strings.Contains(reviewText, "identity: \"\"") || !strings.Contains(reviewText, "variant: \"\"") {
		t.Fatalf("expected blank editable identity/variant fields to remain visible, got:\n%s", reviewText)
	}

	review, legacyFormat, err := readReviewDocument(reviewBytes)
	if err != nil {
		t.Fatalf("readReviewDocument returned error: %v", err)
	}
	if legacyFormat {
		t.Fatal("expected written review YAML to use the current format")
	}
	if got := len(review.Tracks); got != 1 {
		t.Fatalf("expected one review track, got %d", got)
	}
	if got := review.Tracks[0].ID; got != 1 {
		t.Fatalf("expected review id 1, got %d", got)
	}
	if got := len(review.Tracks[0].InternalVector); got != 0 {
		t.Fatalf("expected no embedded vector in YAML, got len=%d", got)
	}
	if got := review.Tracks[0].InternalCount; got != 0 {
		t.Fatalf("expected no embedded internal_count in YAML, got %d", got)
	}
	if review.Tracks[0].Thumbnail != "" {
		t.Fatalf("expected no thumbnail path in YAML, got %q", review.Tracks[0].Thumbnail)
	}

	sidecarBytes, err := os.ReadFile(reviewDataFilePath(reviewPath))
	if err != nil {
		t.Fatalf("failed to read review sidecar: %v", err)
	}

	var sidecar ReviewSidecarDocument
	if err := json.Unmarshal(sidecarBytes, &sidecar); err != nil {
		t.Fatalf("failed to unmarshal review sidecar: %v", err)
	}

	data, ok := sidecar.Tracks["1"]
	if !ok {
		t.Fatalf("expected sidecar data for review id 1, got %+v", sidecar.Tracks)
	}
	if got := len(data.InternalVector); got != embeddingDim {
		t.Fatalf("expected %d vector dimensions, got %d", embeddingDim, got)
	}
	if got := data.InternalCount; got != 3 {
		t.Fatalf("expected internal_count 3, got %d", got)
	}
}

func TestHydrateReviewDocumentLoadsSidecarData(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	reviewPath := filepath.Join(tmpDir, "scan.review.yaml")

	vec := make([]float64, embeddingDim)
	vec[1] = 1.0

	if err := writeReviewSidecarFile(reviewDataFilePath(reviewPath), ReviewSidecarDocument{
		Tracks: map[string]ReviewTrackData{
			"1": {
				InternalVector: vec,
				InternalCount:  2,
			},
		},
	}); err != nil {
		t.Fatalf("writeReviewSidecarFile returned error: %v", err)
	}

	review := ReviewDocument{
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{
				ID:     1,
				Action: "new_identity",
			},
		},
	}

	hydrated, err := hydrateReviewDocument(reviewPath, review)
	if err != nil {
		t.Fatalf("hydrateReviewDocument returned error: %v", err)
	}

	if got := len(hydrated.Tracks[0].InternalVector); got != embeddingDim {
		t.Fatalf("expected %d vector dimensions after hydration, got %d", embeddingDim, got)
	}
	if got := hydrated.Tracks[0].InternalCount; got != 2 {
		t.Fatalf("expected internal_count 2 after hydration, got %d", got)
	}
}

func TestHydrateReviewDocumentAllowsEmbeddedDataWithoutSidecar(t *testing.T) {
	t.Parallel()

	vec := make([]float64, embeddingDim)
	vec[2] = 1.0

	review := ReviewDocument{
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{
				ID:             1,
				Action:         "new_identity",
				InternalVector: vec,
				InternalCount:  1,
			},
		},
	}

	hydrated, err := hydrateReviewDocument(filepath.Join(t.TempDir(), "scan.review.yaml"), review)
	if err != nil {
		t.Fatalf("expected embedded data to bypass sidecar loading, got error: %v", err)
	}
	if got := len(hydrated.Tracks[0].InternalVector); got != embeddingDim {
		t.Fatalf("expected embedded vector to be preserved, got len=%d", got)
	}
}

func TestHydrateReviewDocumentRequiresSidecarForActionableTracks(t *testing.T) {
	t.Parallel()

	reviewPath := filepath.Join(t.TempDir(), "scan.review.yaml")
	review := ReviewDocument{
		VideoID:   "vid_test",
		InputPath: "samples/test.mp4",
		Tracks: []StagingItem{
			{
				ID:     1,
				Action: "new_identity",
			},
		},
	}

	_, err := hydrateReviewDocument(reviewPath, review)
	if err == nil {
		t.Fatal("expected missing sidecar to be rejected")
	}
	if !strings.Contains(err.Error(), reviewDataFilePath(reviewPath)) {
		t.Fatalf("expected missing sidecar path in error, got: %v", err)
	}
}

func TestPrepareReviewArtifactsRootClearsStaleTracks(t *testing.T) {
	t.Parallel()

	resultsDir := t.TempDir()
	staleFile := filepath.Join(resultsDir, "tracks", "1", "frames", "stale.jpg")
	if err := os.MkdirAll(filepath.Dir(staleFile), 0755); err != nil {
		t.Fatalf("failed to create stale artifact dir: %v", err)
	}
	if err := os.WriteFile(staleFile, []byte("stale"), 0644); err != nil {
		t.Fatalf("failed to seed stale artifact: %v", err)
	}

	if err := prepareReviewArtifactsRoot(resultsDir); err != nil {
		t.Fatalf("prepareReviewArtifactsRoot returned error: %v", err)
	}

	if _, err := os.Stat(staleFile); !os.IsNotExist(err) {
		t.Fatalf("expected stale artifact to be removed, stat err=%v", err)
	}
	if info, err := os.Stat(filepath.Join(resultsDir, "tracks")); err != nil {
		t.Fatalf("expected tracks root to be recreated, got error: %v", err)
	} else if !info.IsDir() {
		t.Fatalf("expected recreated tracks root to be a directory")
	}
}

func TestReviewArtifactCommentRootMatchesRuntimeMode(t *testing.T) {
	t.Parallel()

	if got := reviewArtifactCommentRoot("/data", "vid_test"); got != filepath.Join("results", "vid_test", "tracks") {
		t.Fatalf("expected docker comment root to be host-facing results path, got %q", got)
	}
	if got := reviewArtifactCommentRoot("data", "vid_test"); got != filepath.Join("data", "results", "vid_test", "tracks") {
		t.Fatalf("expected local comment root to include data/ prefix, got %q", got)
	}
}
